package com.trava.utilities.webservices.models

data class AppDetail(
        var user_detail_id: Int?=null,
        var user_id: Int?=null,
        var user_type_id: Int?=null,
        var language_id: Int?=null,
        var category_id: Int?=null,
        var category_brand_id: Int?=null,
        var organisation_id: Int?=null,
        var online_status: String?=null,
        var profile_pic: String?=null,
        var profile_pic_url: String?=null,
        var access_token: String?=null,
        var latitude: Double?=null,
        var longitude: Double?=null,
        var timezone: String?=null,
        var timezonez: String?=null,
        var socket_id: String?=null,
        var fcm_id: String?=null,
        var mulkiya_number: String?=null,
        var mulkiya_front: String?=null,
        var mulkiya_back: String?=null,
        var mulkiya_validity: String?=null,
        var maximum_rides: Int?=null,
        var approved: String?=null,
        var mulkiya_front_url: String?=null,
        var mulkiya_back_url: String?=null,
        var user: User?=null,
        var rating_count: Int?=null,
        var ratings_avg: Int?=null,
        var notifications: String?=null,
        val vehicle_color: String?=null,
        val vehicle_name: String?=null,
        var minBalance : Float?=null,
        var km_earned:Int?=null
)