package com.trava.user.webservices.models.homeapi

data class Details(
        var user_detail_id: Int?,
        var user_id: Int?,
        var user_type_id: Int?,
        var language_id: Int?,
        var category_id: Int?,
        var category_brand_id: Int?,
        var organisation_id: Int?,
        var online_status: String?,
        var otp: String?,
        var password: String?,
        var profile_pic: String?,
        var access_token: String?,
        var latitude: Double?,
        var longitude: Double?,
        var timezone: String?,
        var timezonez: String?,
        var socket_id: String?,
        var fcm_id: String?,
        var mulkiya_number: String?,
        var mulkiya_front: String?,
        var mulkiya_back: String?,
        var mulkiya_validity: Any?,
        var created_by: String?,
        var blocked: String?,
        var forgot_token: Any?,
        var forgot_token_validity: Any?,
        var maximum_rides: Int?,
        var created_at: String?,
        var km_earned: Int?,
        var updated_at: String?,
        var user: User?,
        var Org: Any?
)