package com.trava.user.webservices.models.order

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Payment(
        var payment_id: Int?,
        var payment_type: String?,
        var payment_status: String?,
        var refund_status: String?,
        var transaction_id: String?,
        var refund_id: String?,
        var buraq_percentage: Float?,
        var product_actual_value: String?,
        var product_quantity: Int?,
        var product_weight: String?,
        var order_distance: String?,
        var order_time : String?,
        var payment_body : String?,
        var product_alpha_charge: String?,
        var product_per_quantity_charge: String?,
        var product_per_weight_charge: String?,
        var product_per_distance_charge: String?,
        var initial_charge: String?,
        var admin_charge: String?,
        var bank_charge: String?,
        var final_charge: String?,
        var level_charge: String?,
        var bottle_charge: String?,
        var bottle_returned_value: Int?,
        var product_per_hr_charge: String?,
        var product_per_sq_mt_charge: String?,
        var cancellation_charges: Double?,
        var load_unload_charges: Double?,
        var helper_charges: Double?,
        var schedule_charge: Double?,
        var insurance_amount: Double?,
        var sur_charge: Double?,
        var extra_distance: String?,
        var extra_time : String?,
        var toll_charges : Double?,
        var coupon_charge : Double?,
        var toll_images : String?,
        var parking_charges : Double?,
        var airport_charges : Double?,
        var parking_images : String?,
        var price_per_km:Double?,
        var price_per_min: Double?,
        var distance_price_fixed:Double?,
        var distance_kms:Double?,
        var package_type:String?,
        var time_fixed_price:Double?,
        var previous_charges: Double?,
        var zone_charges: Double?,
        var waiting_charges: Double?,
        var isr_mexico_tax: Double?,
        var in_trip_waiting_time: Double?,
        var waiting_time: String?,
        var km_bonus: String?
):Parcelable